#!/usr/bin/env bash
# @spec L2-DEVOPS-01
# Remote fragment: nvm-managed Node 24 + corepack (yarn 4) + pm2, installed
# under the app user, plus the pm2 boot-persistence systemd unit.
# Env: APP_USER, NVM_VERSION.
set -euo pipefail

: "${APP_USER:?APP_USER not set}"
: "${NVM_VERSION:?NVM_VERSION not set}"

if [ "$(id -u)" -eq 0 ]; then SUDO=""; else SUDO="sudo"; fi
APP_HOME="$(getent passwd "$APP_USER" | cut -d: -f6)"

# nvm-managed Node, installed under the app user. pm2 + yarn ride the nvm node.
echo "--> nvm + node 24 + corepack + pm2 (as $APP_USER)"
sudo -H -u "$APP_USER" NVM_VERSION="$NVM_VERSION" bash -s <<'APPSETUP'
set -euo pipefail
cd "$HOME"   # sudo keeps the invoking cwd; an inaccessible cwd makes node spawns fail EACCES
export NVM_DIR="$HOME/.nvm"
if [ -s "$NVM_DIR/nvm.sh" ]; then
  echo "    nvm already installed, skipping"
else
  echo "    installing nvm $NVM_VERSION"
  curl -fsSL "https://raw.githubusercontent.com/nvm-sh/nvm/$NVM_VERSION/install.sh" | bash
fi
# shellcheck disable=SC1091
. "$NVM_DIR/nvm.sh"

if nvm ls 24 >/dev/null 2>&1; then
  echo "    node 24 already installed via nvm, skipping"
else
  echo "    installing node 24 via nvm"
  nvm install 24
fi
nvm alias default 24 >/dev/null
nvm use default >/dev/null

echo "    corepack (yarn 4 via repo packageManager pin)"
corepack enable

if command -v pm2 >/dev/null 2>&1; then
  echo "    pm2 already installed, skipping"
else
  echo "    installing pm2"
  npm i -g pm2
fi
node -v; pm2 -v
APPSETUP

# Boot persistence: pm2-<app-user> systemd unit. Generated by root with the
# app user's nvm node bin on PATH, so the unit finds node without a profile.
NODE_BIN="$(sudo -H -u "$APP_USER" bash -c 'cd; . "$HOME/.nvm/nvm.sh" >/dev/null 2>&1 && dirname "$(command -v node)"')"
if systemctl list-unit-files | grep -q "pm2-$APP_USER"; then
  echo "--> pm2 startup unit present, skipping"
else
  echo "--> pm2 boot persistence (pm2-$APP_USER)"
  $SUDO env PATH="$NODE_BIN:$PATH" "$NODE_BIN/pm2" startup systemd -u "$APP_USER" --hp "$APP_HOME"
fi
